<?php

use App\Models\FloatParam;
use App\Models\StringParam;
use App\Models\TextParam;

return [
    'ASSIGNMENT_AVG_HPD'                   => ['type' => FloatParam::class, 'history' => true],
    'ASSIGNMENT_HOURS_PLANNED'             => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_ANNUAL_EXPENSES'             => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_BANK_BALANCE'                => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_COMPANIES_TIMEBASED'         => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_CUSTOMER_SUPPORT'            => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_INVOICES'                    => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_INVOICES_PREPARED'           => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_INVOICES_RECURRING'          => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_INVOICES_REPAYMENTS'         => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_INVOICES_REPAYMENTS_OVERDUE' => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_PROJECTS'                    => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_PROJECTS_ACQUISITIONS'       => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_PROJECTS_LINREG'             => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_PROJECTS_LINREG_%'           => ['type' => FloatParam::class, 'history' => true],
    'CASHFLOW_PROJECTS_TIMEBASED'          => ['type' => FloatParam::class, 'history' => true],
    'CUSTOMER_NUMBER_CURRENT'              => ['type' => FloatParam::class, 'history' => false],
    'CUSTOMER_NUMBER_PREFIX'               => ['type' => StringParam::class, 'history' => false],
    'CUSTOMER_NUMBER_SUFFIX'               => ['type' => StringParam::class, 'history' => false],
    'DASHBOARDS'                           => ['type' => StringParam::class, 'history' => true],
    'DATEV_MAIL_OUTGOING'                  => ['type' => StringParam::class, 'history' => false],
    'HR_HOURS_12M'                         => ['type' => FloatParam::class, 'history' => true],
    'HR_HOURS_ALL'                         => ['type' => FloatParam::class, 'history' => true],
    'HR_HOURS_INVESTED'                    => ['type' => FloatParam::class, 'history' => true],
    'HR_HOURS_SUPPORT'                     => ['type' => FloatParam::class, 'history' => true],
    'HR_HOURLY_WAGE'                       => ['type' => FloatParam::class, 'history' => true],
    'HR_HPD'                               => ['type' => FloatParam::class, 'history' => true],
    'HR_WORKDAYS'                          => ['type' => FloatParam::class, 'history' => true],
    'INVOICE_CANCEL_PREFIX'                => ['type' => StringParam::class, 'history' => false],
    'INVOICE_CANCEL_SUFFIX'                => ['type' => StringParam::class, 'history' => false],
    'INVOICE_CANCEL_TITLE'                 => ['type' => StringParam::class, 'history' => false],
    'INVOICE_DAY_UNIT'                     => ['type' => StringParam::class, 'history' => false],
    'INVOICE_DD_IBAN'                      => ['type' => StringParam::class, 'history' => false],
    'INVOICE_DD_MANDATE'                   => ['type' => StringParam::class, 'history' => false],
    'INVOICE_DEFAULT_VAT'                  => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_DEG_12M'                      => ['type' => FloatParam::class, 'history' => true],
    'INVOICE_DISCOUNT'                     => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_DOWNLOAD'                     => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_EMAIL_SUBJECT'                => ['type' => StringParam::class, 'history' => false],
    'INVOICE_EMAIL_TEXT'                   => ['type' => TextParam::class, 'history' => false],
    'INVOICE_EMAIL_TEXT_SEPA'              => ['type' => TextParam::class, 'history' => false],
    'INVOICE_FIRST_TS'                     => ['type' => TextParam::class, 'history' => false],
    'INVOICE_GRACE_PERIOD'                 => ['type' => FloatParam::class, 'history' => false, 'default' => 7],
    'INVOICE_HOUR_UNIT'                    => ['type' => StringParam::class, 'history' => false],
    'INVOICE_HOURLY_WAGE'                  => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_HPD'                          => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_M1_PREFIX'                    => ['type' => TextParam::class, 'history' => false],
    'INVOICE_M1_SUFFIX'                    => ['type' => TextParam::class, 'history' => false],
    'INVOICE_M2_PREFIX'                    => ['type' => TextParam::class, 'history' => false],
    'INVOICE_M2_SUFFIX'                    => ['type' => TextParam::class, 'history' => false],
    'INVOICE_NO_CURRENT'                   => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_NO_DIGITS'                    => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_NO_PREFIX'                    => ['type' => StringParam::class, 'history' => false],
    'INVOICE_NO_SUFFIX'                    => ['type' => StringParam::class, 'history' => false],
    'INVOICE_OVERDRAFT_INTEREST'           => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_PAYMENT_DURATION'             => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_PERC_UNIT'                    => ['type' => StringParam::class, 'history' => false],
    'INVOICE_PREFIX'                       => ['type' => TextParam::class, 'history' => false],
    'INVOICE_REMINDER_EMAIL_SUBJECT'       => ['type' => StringParam::class, 'history' => false],
    'INVOICE_REMINDER_EMAIL_TEXT'          => ['type' => TextParam::class, 'history' => false],
    'INVOICE_REMINDER_FEE'                 => ['type' => FloatParam::class, 'history' => false],
    'INVOICE_REVENUE_12M'                  => ['type' => FloatParam::class, 'history' => true],
    'ML_PREDICTED_REVENUE_12M'             => ['type' => FloatParam::class, 'history' => true],
    'ML_PREDICTED_INTERVAL_DAYS'           => ['type' => FloatParam::class, 'history' => true],
    'ML_CHURN_PROBABILITY_12M'             => ['type' => FloatParam::class, 'history' => true],
    'ML_PREDICTED_SUPPORT_HOURS'           => ['type' => FloatParam::class, 'history' => true],
    // JSON reliability summaries (cross-validated, written at train time) — see
    // App\Console\Commands\Concerns\PersistsMlReliability. Global (not per-company/project).
    'ML_RELIABILITY_CUSTOMER_REVENUE'      => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_CUSTOMER_INTERVAL'     => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_CUSTOMER_CHURN'        => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_PROJECT_HOURS'         => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_PROJECT_OVERRUN'       => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_PROJECT_QUOTE_ACCEPTANCE' => ['type' => TextParam::class,  'history' => false],
    'ML_RELIABILITY_SUPPORT_LOAD'          => ['type' => TextParam::class,  'history' => false],
    'INVOICE_SUFFIX'                       => ['type' => TextParam::class, 'history' => false],
    'ME_BIC'                               => ['type' => StringParam::class, 'history' => false],
    'ME_COMPANY_OWNERS'                    => ['type' => StringParam::class, 'history' => false],
    'ME_COUNTRY_SUBDIVISION_NAME'          => ['type' => StringParam::class, 'history' => false],
    'ME_CREDITOR_ID'                       => ['type' => StringParam::class, 'history' => false],
    'ME_DEPARTMENT'                        => ['type' => StringParam::class, 'history' => false],
    'ME_DUNS'                              => ['type' => StringParam::class, 'history' => false],
    'ME_EMAIL'                             => ['type' => StringParam::class, 'history' => false],
    'ME_FAX'                               => ['type' => StringParam::class, 'history' => false],
    'ME_HREG_NAME'                         => ['type' => StringParam::class, 'history' => false],
    'ME_HREG_NO'                           => ['type' => StringParam::class, 'history' => false],
    'ME_IBAN'                              => ['type' => StringParam::class, 'history' => false],
    'ME_ID'                                => ['type' => FloatParam::class, 'history' => false],
    'ME_NAME'                              => ['type' => StringParam::class, 'history' => false],
    'ME_PHONE'                             => ['type' => StringParam::class, 'history' => false],
    'ME_SWIFT'                             => ['type' => StringParam::class, 'history' => false],
    'ME_TAX_ID'                            => ['type' => StringParam::class, 'history' => false],
    'ME_VAT_ID'                            => ['type' => StringParam::class, 'history' => false],
    'ME_VATID'                             => ['type' => StringParam::class, 'history' => false],
    'PROJECT_PAYMENT_PLAN'                 => ['type' => TextParam::class, 'history' => false],
    'PROJECT_PAYMENT_PLAN_TIERS'           => ['type' => TextParam::class, 'history' => false],
    'PROJECT_PREFIX'                       => ['type' => TextParam::class, 'history' => false],
    'PROJECTS_POSTPONE_WITH_COMMENT'       => ['type' => FloatParam::class, 'history' => false],
    'PROJECT_SUFFIX'                       => ['type' => TextParam::class, 'history' => false],
    'PROJECT_WARRANTY_DURATION'            => ['type' => FloatParam::class, 'history' => false, 'default' => 1],
    'PROJECT_LEGAL'                        => ['type' => TextParam::class, 'history' => false],
    'QUOTE_NO_CURRENT'                     => ['type' => FloatParam::class, 'history' => false],
    'QUOTE_NO_DIGITS'                      => ['type' => FloatParam::class, 'history' => false],
    'QUOTE_NO_PREFIX'                      => ['type' => StringParam::class, 'history' => false],
    'QUOTE_NO_SUFFIX'                      => ['type' => StringParam::class, 'history' => false],
    'QUOTE_VALIDITY_DURATION'              => ['type' => FloatParam::class, 'history' => false, 'default' => 30],
    'PROJECT_SUCCESS_RATE'                 => ['type' => FloatParam::class, 'history' => true],
    'PROJECT_CREATE_AUTO_BUDGET'           => ['type' => FloatParam::class, 'history' => false, 'default' => 2],
    'MILESTONE_CONVERSION_FACTOR'          => ['type' => FloatParam::class, 'history' => false, 'default' => 1.5],
    'STATS_LINREG_FORMULA'                 => ['type' => TextParam::class, 'history' => true],
    'STATS_LINREG_FORECAST_12M'            => ['type' => FloatParam::class, 'history' => true],
    'STATS_LINREG_STANDARD_ERROR'          => ['type' => FloatParam::class, 'history' => true],
    'STATS_LINREG_R2'                      => ['type' => FloatParam::class, 'history' => true],
    'STATS_PREDICTION_BIAS'                => ['type' => FloatParam::class, 'history' => true],
    'STATS_FOCUS_ACCURACY'                 => ['type' => FloatParam::class, 'history' => true],
    'STATS_INVOICEITEM_FOCUS'              => ['type' => FloatParam::class, 'history' => true],
    'SYS_COUNTRY'                          => ['type' => StringParam::class, 'history' => false],
    'SYS_CURRENCY'                         => ['type' => StringParam::class, 'history' => false],
    'SYS_LANGUAGE'                         => ['type' => StringParam::class, 'history' => false],
    'SYS__SENTINEL_LAST_CHECK'             => ['type' => FloatParam::class, 'history' => false],
    'VACATION_MAIL_APPROVED'               => ['type' => TextParam::class, 'history' => false],
    'VACATION_MAIL_DENIED'                 => ['type' => TextParam::class, 'history' => false],

    // Marketing Assets Category Descriptions
    'MARKETING_BRAND_ASSETS_DESC'            => ['type' => TextParam::class, 'history' => false],
    'MARKETING_SOCIAL_MEDIA_DESC'            => ['type' => TextParam::class, 'history' => false],
    'MARKETING_EMAIL_TEMPLATES_DESC'         => ['type' => TextParam::class, 'history' => false],
    'MARKETING_PRESENTATIONS_DESC'           => ['type' => TextParam::class, 'history' => false],
    'MARKETING_PRINT_MATERIALS_DESC'         => ['type' => TextParam::class, 'history' => false],
    'MARKETING_VIDEO_CONTENT_DESC'           => ['type' => TextParam::class, 'history' => false],
    'MARKETING_DOCUMENTS_DESC'               => ['type' => TextParam::class, 'history' => false],
    'VACATION_MAIL_SUBJECT'                  => ['type' => StringParam::class, 'history' => false],
    'AUDIT_DEFAULT_PRODUCT_ID'               => ['type' => FloatParam::class,  'history' => false],
    'SETTINGS_GIT_PIPELINE'                  => ['type' => TextParam::class,   'history' => false],
    'WEBDAV_TOKEN'                           => ['type' => StringParam::class, 'history' => false],
    'NOTIFICATION_EMAIL_ON_FRAMEWORK_UPDATE' => ['type' => StringParam::class, 'history' => false],
    'PROJECT_WORK_THRESHOLDS'                => ['type' => TextParam::class, 'history' => false],
    'PROJECT_WORK_THRESHOLD_NOTIFIED'        => ['type' => TextParam::class, 'history' => false],
    'PROJECT_PREDICTED_OVERRUN_THRESHOLDS'   => ['type' => TextParam::class, 'history' => false],
    'PROJECT_OVERRUN_WARN_THRESHOLD'         => ['type' => FloatParam::class, 'history' => false, 'default' => 110],
    'PROJECT_PREDICTED_OVERRUN_NOTIFIED'     => ['type' => TextParam::class, 'history' => false],
];
