/**
 * Model Registry - Auto-generated model path mappings
 *
 * This file is AUTO-GENERATED by scripts/generate-model-registry.js
 * DO NOT EDIT MANUALLY - Run 'npm run generate:models' to regenerate
 *
 * This file maps model class names to their class constructors for dynamic instantiation.
 */

import { Assignee } from '@models/assignee/assignee.model';
import { CalendarEntry } from '@models/vcalendar/calendar-entry.model';
import { Cash } from '@models/cash/cash.model';
import { CashRegister } from '@models/cash/cash.register.model';
import { Comment } from '@models/comment/comment.model';
import { Company } from '@models/company/company.model';
import { CompanyContact } from '@models/company/company-contact.model';
import { Connection } from '@models/company/connection.model';
import { ConnectionProjects } from '@models/company/connection-projects.model';
import { Contact } from '@models/company/contact.model';
import { DebriefPositive } from '@models/project/debrief-positive.model';
import { DebriefProblem } from '@models/project/debrief-problem.model';
import { DebriefProblemCategory } from '@models/project/debrief-problem-category.model';
import { DebriefProjectDebrief } from '@models/project/debrief-project-debrief.model';
import { DebriefSolution } from '@models/project/debrief-solution.model';
import { DeletionLog } from '@models/deletion-log/deletion-log.model';
import { Encryption } from '@models/encryption/encryption.model';
import { Expense } from '@models/expense/expense.model';
import { ExpenseCategory } from '@models/expense/expense-category.model';
import { File } from '@models/file/file.model';
import { Focus } from '@models/focus/focus.model';
import { Framework } from '@models/project/framework.model';
import { FrameworkLatest } from '@models/project/framework-latest.model';
import { GitlabAuditProject } from '@models/gitlab-audit/gitlab-audit-project.model';
import { GitlabSchedule } from '@models/gitlab-audit/gitlab-schedule.model';
import { Invoice } from '@models/invoice/invoice.model';
import { InvoiceItem } from '@models/invoice/invoice-item.model';
import { InvoiceReminder } from '@models/invoice/invoice-reminder.model';
import { LeadSource } from '@models/project/lead-source.model';
import { MarketingActivity } from '@models/marketing/marketing-activity.model';
import { MarketingInitiative } from '@models/marketing/marketing-initiative.model';
import { MarketingInitiativeActivity } from '@models/marketing/marketing-initiative-activity.model';
import { MarketingPerformanceMetric } from '@models/marketing/marketing-performance-metrics.model';
import { MarketingProspect } from '@models/marketing/marketing-prospect.model';
import { MarketingProspectActivity } from '@models/marketing/marketing-prospect-activity.model';
import { MarketingProspectStats } from '@models/marketing/marketing-prospect-stats.model';
import { MarketingWorkflow } from '@models/marketing/marketing-workflow.model';
import { Milestone } from '@models/milestone/milestone.model';
import { MilestoneData } from '@models/milestone/milestone-group.model';
import { MilestonesGroup } from '@models/milestone/milestone-group.model';
import { Param } from '@models/param/param.model';
import { PluginLink } from '@models/plugin-link/plugin-link.model';
import { Prediction } from '@models/prediction.model';
import { Product } from '@models/product/product.model';
import { ProductGroup } from '@models/product/product-group.model';
import { Project } from '@models/project/project.model';
import { ProjectState } from '@models/project/project-state.model';
import { Sentinel } from '@models/sentinel/sentinel.model';
import { Task } from '@models/task/task.model';
import { UptimeCheck } from '@models/uptime/uptime-check.model';
import { UptimeMonitor } from '@models/uptime/uptime-monitor.model';
import { User } from '@models/user/user.model';
import { UserEmployment } from '@models/user/user-employment.model';
import { Vacation } from '@models/vacation/vacation.model';
import { VacationGrant } from '@models/vacation/vacation-grant.model';
import { Vault } from '@models/vault.model';

export const MODEL_REGISTRY: Record<string, any> = {
    'Assignee': Assignee,
    'CalendarEntry': CalendarEntry,
    'Cash': Cash,
    'CashRegister': CashRegister,
    'Comment': Comment,
    'Company': Company,
    'CompanyContact': CompanyContact,
    'Connection': Connection,
    'ConnectionProjects': ConnectionProjects,
    'Contact': Contact,
    'DebriefPositive': DebriefPositive,
    'DebriefProblem': DebriefProblem,
    'DebriefProblemCategory': DebriefProblemCategory,
    'DebriefProjectDebrief': DebriefProjectDebrief,
    'DebriefSolution': DebriefSolution,
    'DeletionLog': DeletionLog,
    'Encryption': Encryption,
    'Expense': Expense,
    'ExpenseCategory': ExpenseCategory,
    'File': File,
    'Focus': Focus,
    'Framework': Framework,
    'FrameworkLatest': FrameworkLatest,
    'GitlabAuditProject': GitlabAuditProject,
    'GitlabSchedule': GitlabSchedule,
    'Invoice': Invoice,
    'InvoiceItem': InvoiceItem,
    'InvoiceReminder': InvoiceReminder,
    'LeadSource': LeadSource,
    'MarketingActivity': MarketingActivity,
    'MarketingInitiative': MarketingInitiative,
    'MarketingInitiativeActivity': MarketingInitiativeActivity,
    'MarketingPerformanceMetric': MarketingPerformanceMetric,
    'MarketingProspect': MarketingProspect,
    'MarketingProspectActivity': MarketingProspectActivity,
    'MarketingProspectStats': MarketingProspectStats,
    'MarketingWorkflow': MarketingWorkflow,
    'Milestone': Milestone,
    'MilestoneData': MilestoneData,
    'MilestonesGroup': MilestonesGroup,
    'Param': Param,
    'PluginLink': PluginLink,
    'Prediction': Prediction,
    'Product': Product,
    'ProductGroup': ProductGroup,
    'Project': Project,
    'ProjectState': ProjectState,
    'Sentinel': Sentinel,
    'Task': Task,
    'UptimeCheck': UptimeCheck,
    'UptimeMonitor': UptimeMonitor,
    'User': User,
    'UserEmployment': UserEmployment,
    'Vacation': Vacation,
    'VacationGrant': VacationGrant,
    'Vault': Vault,
};
